CREATE TABLE `GROND_PERSOON` (
  `ID` int(11) NOT NULL auto_increment,
  `FK_GROND_ID` int(11) NOT NULL,
  `FK_PERSOON_ID` int(11) NOT NULL,
  PRIMARY KEY  (`ID`,`FK_GROND_ID`,`FK_PERSOON_ID`)
) ENGINE=MyISAM