CREATE TABLE `KASBON` (
  `ID` int(11) NOT NULL auto_increment,
  `AANTAL_NACHTEN` int(11) NOT NULL default '1',
  `AUTO100` int(11) NOT NULL default '0',
  `AUTO150` int(11) NOT NULL default '0',
  `WAARBORG` int(11) NOT NULL default '0',
  `JETON` int(11) NOT NULL default '0',
  `ZAK_GEEL` int(11) NOT NULL default '0',
  `ZAK_BLAUW` int(11) NOT NULL default '0',
  `CAR` int(11) NOT NULL default '0',
  `TENT` int(11) NOT NULL default '0',
  `VOLWASSENEN` int(11) NOT NULL default '0',
  `KINDEREN` int(11) NOT NULL default '0',
  `TELEFOON` double NOT NULL default '0',
  `KASBON_DATUM` date default NULL,
  `NAAM` varchar(255) NOT NULL default 'Kassa',
  `STANDPLAATS` varchar(10) default NULL,
  `NUMMERPLAAT` varchar(12) default NULL,
  `BADGE` varchar(20) default NULL,
  `DATUM_VAN` date default NULL,
  `DATUM_TOT` date default NULL,
  `BETALING` double default '0',
  `TERUG` double default '0',
  PRIMARY KEY  (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8